### ISSUE TITLE
Add new form templates

### ISSUE THREAD

**Issue by Shelob9** [CalderaWP/Caldera-Forms#1149]

**Comment by andrewlimaza** [comment]
I'm pretty keen for this ;)

**Comment by Shelob9** [comment]
Send ideas! Send templates!

**Comment by paaljoachim** [comment]
What do you mean with form templates?

**Comment by Shelob9** [comment]
Assigning to @andrewlimaza -- Please submit some PRs on monday so we can ship beta

**Comment by paaljoachim** [comment]
What about making it possible for the user to save a form as a template so that a thumbnail image version of it shows up in the new form from template section?

Then a folder inside of CF plugin folder named temp or template (or something like it) to where we can manually add exported forms. Our own or someone elses that have shared their form. These would then show up in the new form template section.

**Comment by andrewlimaza** [comment]
@shelob9 working on a couple more templates this morning, will push out a PR today for you.

**Comment by andrewlimaza** [comment]
@Shelob9 here is the PR ->https://github.com/CalderaWP/Caldera-Forms/pull/1180

@paaljoachim I'm sure it's possible, the idea interests me. Maybe create a new issue for this feature 👍

**Comment by paaljoachim** [comment]
I just made a new issue:
#1181

**Comment by Shelob9** [comment]
Close via #1180
