### ISSUE TITLE
EDIT ENTRY malfunction in caldera forms 1.5.0.4

### ISSUE THREAD

**Issue by rachellann** [CalderaWP/Caldera-Forms#1343]
In page wordpress/wp-admin/admin.php?page=caldera-forms
After attaching file to the upload button then entering with the View button the Edit Entry offering returns an empty list…

**Comment by Shelob9** [comment]
@rachellann Thanks for using Caldera Forms. I'm sorry you're having this problem, but I can't help as I have no idea what the problem is. If you can provide information about PHP and JavaScript errors as was detailed in the issue template, you are encountering I could understand if this is a conflict with your site or a bug. Right now, I have nothing to go on.

Also, please keep in mind this is not a support channel. If you need help troubleshooting an issue, please open a ticket at https://calderaforms.com/support
