### ISSUE TITLE
Validation translation not loading properly

### ISSUE THREAD

**Issue by tomygrenier** [CalderaWP/Caldera-Forms#1400]
## What Version Of Caldera Forms, WordPress and PHP Are You Using?
WordPress Version: 4.7.2PHP Version: 5.5.36MySQL Version: 5.7.9Caldera Forms Version: 1.5.0.5WP_DEBUG: 1
Using fr_CA language.

## Does Your Issue Persist When You Disable All Other Plugins and Switch To The Default Theme?
Yes

## What Is The Unexpected Behaviour?
I updated Caldera to 1.5.0.4 and then to 1.5.0.5 and I had to recreate existing forms (before updates) because they no longer work.

AND

Parsley file didn't work. I tried the suggested «add_filter( 'caldera_forms_render_assets_minify', '__return_false' )» hook for version 1.5.0.4. But I still have the «This value is required» message in english on form validation.

 
## What PHP Errors Have You Logged While Reproducing This Bug?
None

## What JavaScript Errors Have You Seen While Reproducing This Bug?
None

Thanks!
Tomy

**Comment by Shelob9** [comment]
What language did you set your site to in WordPress?

**Comment by tomygrenier** [comment]
I'm «Using fr_CA language».

**Comment by tomygrenier** [comment]
The /caldera-forms/assets/js/i18n/fr.js?ver=1.5.0.5 file is called in <head> but it seems it is not working.

**Comment by G3ronim0** [comment]
Hi, same for me WP locale is : fr_FR. Thanks

**Comment by florent-cdl** [comment]
same for me.
I had to force with a script : setTimeout(function(){ window.Parsley.setLocale('fr'); }, 2000);

**Comment by Shelob9** [comment]
Thanks for the report and the details from everyone. 

I think that the solution @florent-cdl  suggests is probably best. I made an example of how to load this in footer- https://gist.github.com/Shelob9/cfa94404a1cb4e725ce2ddf6b3d7ed67

 It suggest that the issue is that the parsley loading of locale is not happening the correct sequence. I will look at how to make this more reliable. Possibly using exactly what @florent-cdl has done.

#1348 is a planned filter for Parsely messages. I'd rather have those be part of translation packs, then have everyone do redundant filter work, or just get the Parsely system to be more reliable. I'm very open to suggestions.

**Comment by depepin** [comment]
Hi there, I'm having the same problem with FR language.

To solve that issue, where the code or file "force-caldera-language.php" should be put?

Thanks

**Comment by Shelob9** [comment]
So, I'm pretty convinced this is beacuse of the translation file loading in the wrong order. I implimented the fix suggested by @florent-cdl in	b89b1c3

**Comment by mrksdiehl** [comment]
If the same form is rendered twice or more times, window.Parsley.setLocale will be added multiple times. Not that it breaks anything but it's not clean. I think it should check if it got added already before writing again. Same problemwith the submit (trigger) event listener.
