### ISSUE TITLE
Skip to particular page

### ISSUE THREAD

**Issue by warudin** [CalderaWP/Caldera-Forms#1644]
Hi,

When using a multipage form, is it possible to skip to a particular page when clicking on a button/link? 

We'd like to use Caldera to walk the user though a sort of wizard where the next page is dependent on choices on the current page.

Currently, it only seems possible to go to the next or previous page, not a certain page number. Is this right?

**Comment by Shelob9** [comment]
If you enable breadcrumbs, they can skip, but if a previous page has a required field, then a validation error will happen, so this isn't a great solution. It sounds like our Connected Forms add-on is  what you need, since it can put multiple forms together into a sequence, using conditional logic to choose which form to load next: https://calderaforms.com/downloads/caldera-forms-connector/

**Comment by warudin** [comment]
OK, thanks for answering.
