### ISSUE TITLE
Empty calculation triggers PHP Warning message about calc.php (line 218) invalid foreach

### ISSUE THREAD

**Issue by skipthedrive** [CalderaWP/Caldera-Forms#1959]
## Do You Need Immediate Help?
No

## Is This A Feature Request?
No

## What Version Of Caldera Forms, WordPress and PHP Are You Using?
WordPress Version: 4.8.1PHP Version: 7.0.21MySQL Version: 5.6.36Caldera Forms Version: 1.5.6.1WP_DEBUG:

## Does Your Issue Persist When You Disable All Other Plugins and Switch To The Default Theme?
If I knew how to recreate the issue I would try it out, but I can't afford to disable my plugins and switch to a default theme. I only get this every couple of days.

## What Is The Unexpected Behaviour?
I'm getting a PHP warning message in my error logs regarding calc.php.  I do not know how to recreate this message.

## What PHP Errors Have You Logged While Reproducing This Bug?
PHP Warning:  Invalid argument supplied for foreach() in /home/xxxxxxxxxx/public_html/wp-content/plugins/caldera-forms/classes/sync/calc.php on line 218

## What JavaScript Errors Have You Seen While Reproducing This Bug?
None

**Comment by Shelob9** [comment]
Thanks for using Caldera Forms. I'm sorry you're having this issue.

I've seen it happen two ways. 

- A field ID magic tag instead of field slug magic tag in a manual calculation
See: https://github.com/CalderaWP/Caldera-Forms/issues/1951#issuecomment-329552041

- A calculation field with no calculation set in it.

Does either of these describe any of the calculations in your forms?

**Comment by skipthedrive** [comment]
Yes, I did have a calculation field with no calculation set. I ended up removing it and replacing it with a HTML element, which fixed it! Thanks :)

**Comment by Shelob9** [comment]
@skipthedrive Thanks for that info and I'm glad you got a solution out of it :)

**Comment by Shelob9** [comment]
Close via 		2614cd4
