### ISSUE TITLE
Weird code appears when "toggle-switch" is selected

### ISSUE THREAD

**Issue by K-GC** [CalderaWP/Caldera-Forms#2004]
_**I am not sure if this is a bug? Or some other sort of error? Please advise on how I can correct this.
Thank you!**_

## What Version Of Caldera Forms, WordPress and PHP Are You Using?
WordPress Version: 4.8.2
PHP Version: 5.6.31
MySQL Version: 10.1.24
Caldera Forms Version: 1.5.6.1

## Does Your Issue Persist When You Disable All Other Plugins and Switch To The Default Theme?
Yes.

## What Is The Unexpected Behaviour?
When I set up a 'toggle-switch' field, the selected option from the toggle-switch produces a weird code below: **/ * ] ] > * /**
<img width="293" alt="conditional option error1" src="https://user-images.githubusercontent.com/32738938/31498912-39d1a1c0-af31-11e7-80f4-c0688729b009.PNG">

**Comment by Shelob9** [comment]
Thanks for using Caldera Forms. This is normally caused by caching plugins or a them applying shortcode regex manually. 

Please note, this is not a support channel.  If you need immediate help with your site or help troubleshooting Caldera Forms on your site, please open a support ticket at https://CalderaForms.com/support
