### ISSUE TITLE
Connected Caldera forms do not advance correctly

### ISSUE THREAD

**Issue by EmilyHazlehurst** [CalderaWP/Caldera-Forms#2084]
## Do You Need Immediate Help?
No

## Is This A Feature Request?
No

## What Version Of Caldera Forms, WordPress and PHP Are You Using?
The issue affects all versions of CF after 1.5.6.1. The Connected CF version is 1.2.1 and the WP version is 4.8.3.

## Does Your Issue Persist When You Disable All Other Plugins and Switch To The Default Theme?
Yes.

## What Is The Unexpected Behaviour?
On clicking next, connected forms progress to the correct next page but the page buffers indefinitely and the fields cannot be interacted with. Refreshing the page allows continuation of the form but the same issue occurs with any subsequent pages.

This happens on all of our forms, regardless of the number of pages.

![image](https://user-images.githubusercontent.com/24455584/32955468-fc0a537a-cbad-11e7-9174-29b14330eb5e.png)

Rolling back to version 1.5.6.1 of Caldera Forms resolves the issue.

## What PHP Errors Have You Logged While Reproducing This Bug?
I was unable to check this.

## What JavaScript Errors Have You Seen While Reproducing This Bug?

![image](https://user-images.githubusercontent.com/24455584/32955796-eb19fd9e-cbae-11e7-8fbb-37eddf7fa086.png)

(The field id is always the ID of the first field on the page with _1 appended to it.)

Thank you in advance!

**Comment by Shelob9** [comment]
This looks like an issue that is fixed in Connected Forms 1.2.2


https://calderaforms.com/updates/connected-caldera-forms-1-2-2/

If you don't have updates  setup through license  manager. You can get the
update by putting your license code into the form on the update post or
logging into your account page at https://calderaforns.com/account

Please try the updated version and if that doesn't help or you have other
needs, please open a support ticket at https://CalderaForms.com/support

**Comment by Shelob9** [comment]
I'm closing this out, as this isn't a bug in the core plugin. Please open a support ticket if you need further help. https://calderaforms.com/support
