### ISSUE TITLE
Success message not translated

### ISSUE THREAD

**Issue by Sarah1101** [CalderaWP/Caldera-Forms#2117]
## What Version Of Caldera Forms, WordPress and PHP Are You Using?
Caldera Forms 1.5.7.1, WordPress 4.9.1, PHP 7.1.11

## Does Your Issue Persist When You Disable All Other Plugins and Switch To The Default Theme?
Yes.

## What Is The Unexpected Behaviour?
The success message to show after form is submitted isn’t translated to German. But in the translation file .po I can find a translation for this. When I create a new form, the english message is in the field for success message, so I have the adapt every single form instead of having the default german text.

**Comment by Shelob9** [comment]
Thanks for using Caldera Forms. Since this is a setting of the form it should not be in the translation files.

The success message can be changed in the "Form Settings" tab. If your site is in one language, that's all you need. If the site is multi-lingual, our free translation plugin can translate that setting for you.
