### ISSUE TITLE
Connected forms

### ISSUE THREAD

**Issue by adelahomutova** [CalderaWP/Caldera-Forms#2210]
Hi,

we would like to use connected forms but either this adddon doesn't work properly or we had different expectations about function.

Here is example for what I need use this addon for:
I need to create an order. To enter this order you have to fill a password. There are many types of next pages of form based on filled password because different passwords means different "users" - different possibilities. And if you try to entry with non-existing password, you shouldn't be able to get to the next page. 

But now in real if you enter wrong password (some password which is not set as a condition for any next page) and click on "next" button, random next page is shown - even those pages which are conditioned by password. 

Is it possible to figure this out to make it work properly?

**Comment by Shelob9** [comment]
@adelahomutova - Thanks for using Caldera Forms. Yes this is possible. If you used our users add-on to manage user login and registration it would be very simple. Connected Forms tracks logged in users. You could do this by setting up 2 extra processors and probably one extra form.

If you need help setting this up, please open a support ticket at https://calderaforms.com/support and we can help. You're paying for priority support already and we can be more helpful there.

I do see that you're asking about the possibility of sort of creating your own user system in the form instead of using WordPress users. That sounds like a good idea, it's not going to work out well. As someone who wrote a large part of this, I can see why it's not obvious that's not going to work out well, but it's really acting against the design of the system.

**Comment by Shelob9** [comment]
BTW I closed this because it's not a Caldera Forms issue that we need to track as part of Caldera Forms development. You're our paying customer, we want to help, just need to close this for house keeping reasons.
