### ISSUE TITLE
Import Issue “File is not a valid Caldera Form Import”

### ISSUE THREAD

**Issue by cmyla** [CalderaWP/Caldera-Forms#2283]
## Do You Need Immediate Help?
Yes, but I have the free plugin, so no support for me.

## Is This A Feature Request?
No

## What Version Of Caldera Forms, WordPress and PHP Are You Using?
WordPress Version: 4.9.2 / PHP Version: 5.6.33 / MySQL Version: 5.6.34 / Caldera Forms Version: 1.5.9.1 

## Does Your Issue Persist When You Disable All Other Plugins and Switch To The Default Theme?
Unfortunelly, Yes.

## What Is The Unexpected Behaviour?
I have a form on a website, i would like to import this form on an other website (after exporting the Json file from the first website, the 2 websites have Caldera forms plugin of course).
When I try to import the Json file on the 2nd website : “File is not a valid Caldera Form Import”.
I have already check for extra lines in the Json file (and there is not)

## What PHP Errors Have You Logged While Reproducing This Bug?
Nothing (back office)

## What JavaScript Errors Have You Seen While Reproducing This Bug?
Failed to load resource: the server responded with a status of 500 ()          admin.php

**Comment by Shelob9** [comment]
@cmyla Thanks for using Caldera Forms. I'm sorry you're having this issue. You said you got "Failed to load resource: the server responded with a status of 500 () admin.php" that means a fatal error happened and you set your server not to report that error.

In order to work through this issue and see if it is a bug or a conflict, we'll need to know what that error is. 

If you'd like to do that yourself, please follow these steps: https://calderaforms.com/2016/05/wordpress-debug-logging/

If not, please purchase a support subscription -- https://calderaforms.com/pro and a member of our team can help you with that.

**Comment by cmyla** [comment]
Hi,
I have already put the _define('WP_DEBUG', true);_  and _define('WP_DEBUG_LOG', true);_ in my wp-config, there is no debug.log file created. I have even put _define('WP_DEBUG_DISPLAY', true);_ and nothin appears...
I don't know what to do

**Comment by cmyla** [comment]
Just for information : I've searched on the web for a solution, I've tried reencoding in "UTF8 without BOM" in Notepadd++ : it's working.
