### ISSUE TITLE
Caldera form PHP issue

### ISSUE THREAD

**Issue by anilparkhe** [CalderaWP/Caldera-Forms#2486]
I have updated the Caldera Plugin latest version and using PHP 7.1.16 but Caldera form still gives me an out of date PHP version error.

![screen shot 2018-05-11 at 2 29 19 pm](https://user-images.githubusercontent.com/39186114/39916411-01ad23e4-5528-11e8-969d-f79b340def28.jpg)

**Comment by Shelob9** [comment]
How sure are you that this site is on PHP 7.1? The message you're showing is generated using the constant `PHP_VERSION` and reports 5.3.29. What does the PHP info plugin report? https://wordpress.org/plugins/wordpress-php-info/

**Comment by anilparkhe** [comment]
![php setting](https://user-images.githubusercontent.com/39186114/39956451-32464b44-55fe-11e8-928e-a534a7076fa3.png)

**Comment by anilparkhe** [comment]
Any comments??

**Comment by Shelob9** [comment]
@anilparkhe That's not helpful information for me. What I need to see is the output of `phpinfo()` for this site. That plugin will show it.

To be honest, I doubt I can help. On your site the constant `PHP_VERSION` is 5.3.29. I know because it's printed in that warning. If your PHP version isn't the same as that constant, than that's a major issue on your server.
