### ISSUE TITLE
New Privacy Consent field

### ISSUE THREAD

**Issue by dshayne** [CalderaWP/Caldera-Forms#2570]
I am using WP version 4.9.6 and Caldera Forms new 1.70.

Thank you for providing a consent field for the forms. However, the page you link to for Privacy Policy is actually the Privacy Tools page. How do I change that link?

Thanks in advance,
Debbie

**Comment by LogoLogics2** [comment]
Hi,

You need to  create the Privacy Policy page using the build in tool in Wordpress ( settings>privacy ).
You can change that name if you like. After that the contactform will link to that page correctly.

Hope this helps,
Annie

**Comment by mchandelier** [comment]
Hi,

Same issue here and I already created my privacy policy page using the build in tool in WordPress.

Thanks for your help,

Mylène

**Comment by Shelob9** [comment]
Thanks for using Caldera Forms. I am closing this issue since it is a support question.

Here is the documentation on how to use a different privacy page link there:
* https://calderaforms.com/doc/caldera_forms_privacy_policy_page_url/

There is documentation of setting up GDPR/privacy features here:
* https://calderaforms.com/doc/setting-caldera-forms-gdpr-data-requests/
* https://calderaforms.com/doc/consent-field/

**Comment by mchandelier** [comment]
@dshayne check if your privacy policy page is published or not. Mine wasn't that's why I got the issue.
