### ISSUE TITLE
After 1.7 update, Fatal error: Call to undefined function get_home_path() in /home/ultimate/www/dev/wp-admin/includes/misc.php on line 204

### ISSUE THREAD

**Issue by cicichirinos** [CalderaWP/Caldera-Forms#2574]
ticket: https://secure.helpscout.net/conversation/593437223/10136?folderId=832043

WordPress Version

4.9.6
PHP Version

5.6.3
Caldera Forms Version

1.7.0
Add-on Version

1.4.1
Errors

Fatal error: Call to undefined function get_home_path() in /home/ultimate/www/dev/wp-admin/includes/misc.php on line 204

**Comment by Festum** [comment]
Me2

**Comment by Shelob9** [comment]
I think this is related to Divi, but I can't reproduce. I did just deactivate Divi and get this error.

**Comment by Shelob9** [comment]
In general this seems to be related to Ultimate Members or Divi. I would recommend contacting their support. I will reach out to Divi team as I know them. Its happening because of rewrite rules being flushed at the wrong place (the definition of wrong place changed in 4.9.6).

**Comment by Shelob9** [comment]
Developer notes:

* We flush rewrites (necessary for the cf-api endpoint) [here](https://github.com/CalderaWP/Caldera-Forms/blob/master/classes/core.php#L486)Should only run on update.
* We used to flush rewrites in a second place, but removed it in 1.7 because of [the WordPress issue introduced in 4.9.6](https://core.trac.wordpress.org/ticket/44142). #2566

**Comment by cycastic** [comment]
I am seeing this same issue.  I am not using either Ultimate Members or Divi and the issue persisted even after I deleted Caldera Forms,  (doing this removed the error and allowed me to log in, so it seems to be clearly a Caldera issue) disabled all plugins, then reinstalled Caldera forms.   

My theme is a lightly customised child theme of twenty thirteen, and all plugins and wordpress core are updated. 

Restoring just the Caldera Forms files  to the previous version didn't work.  I was able to log in and see the Caldera interface when I deleted the new version of the plugin and uploaded a backup version from yesterday, but I was not able to see my forms, presumably because somewhere in the database was an entry saying I had updated. 

I had to roll the entire site back to a backup from yesterday in order to get the whole thing working again.  

Will definitely be testing at a test location first rather than sloppily applying an update live next time!

**Comment by Shelob9** [comment]
I know understand why this is our fault, which is great. Fix incoming.

**Comment by dimbak** [comment]
User reports that downgrading from php7 to 5.6 fixes this error

ticket: https://secure.helpscout.net/conversation/595479797/0/?folderId=832038

**Comment by Shelob9** [comment]
This should be fixed via eced214 and 2e9fb61
If using Ultimate Member plugin and WordPress 4.9.6 this is likely still an issue. See: #2594

**Comment by Shelob9** [comment]
![screen shot 2018-06-08 at 10 58 58 am](https://user-images.githubusercontent.com/1994311/41165657-3574746c-6b0c-11e8-8ca8-d7c17063a86a.png)

**Comment by Shelob9** [comment]
cf2a41a solves the root problem, privacy settings added on a hook that can run in a non-admin context. All issues related to this should be solved now. I will release 1.7.1.4 to WP.org with this fix today.
