### ISSUE TITLE
Caldera Forms are broken

### ISSUE THREAD

**Issue by KJlassi** [CalderaWP/Caldera-Forms#2657]
**Do You Need Immediate Help?**
Yes

**Is This A Feature Request?**
No

**What Version Of Caldera Forms, WordPress and PHP Are You Using?**
Caldera Forms: 1.6.1
WordPress: 
PHP: I'm not sure where to find this

**Does Your Issue Persist When You Disable All Other Plugins and Switch To The Default Theme?**
Not willing to do this-this is a company website. 

**What Is The Unexpected Behaviour?**
I have been having problems with the Caldera Forms plugin. The forms have stopped working on our website, in particular, the buttons no longer function. I had a Wordkeeper agent assist me. He suggested undoing the recent update that was done over the weekend, however, this did not work. He believes there may be a bug in your updated code and suggested I contact you directly. You can see one example of the broken Caldera Forms here: https://www.sunwize.com/mount-guide/. Thanks in advance for the assistance.

**What PHP Errors Have You Logged While Reproducing This Bug?**
I have not reproduced this bug.

**What JavaScript Errors Have You Seen While Reproducing This Bug?**
I have not reproduced this bug.

**I am not a programmer and I do not understand any of this. I was particularly looking to have some sort of assistance solving the problems with this plugin, but there are no service options for those not paying for the plugin. I appreciate the help and hope this document is what you need.

Here is the PHP file. 
[php.docx](https://github.com/CalderaWP/Caldera-Forms/files/2160958/php.docx)**

**Comment by cicichirinos** [comment]
Hi there. GitHub is what we use for tracking software bugs and improving the Caldera Forms product for everybody. It is not a channel for immediate help, which you indicated you need. I would recommend opening a support ticket at calderaforms.com/support and one of our support engineers will help you. As you noted, our support plans are paid offerings. This is the business model by which we are able to offer a feature-rich plugin like Caldera Forms for free and have a professional team of engineers to maintain and support it. Thanks for understanding! 

I will also note that it is essential for us to be able to deactivate your themes and plugins to figure out what has caused the buttons to stop working on your site. I would recommend setting up a staging website and/or a local environment before reaching out to support so that we can be most helpful. DesktopServer is a really great tool for non-devs to accomplish this.
