### ISSUE TITLE
All forms missing after updating Caldera Forms Plugin to 1.7.2

### ISSUE THREAD

**Issue by jarneson79** [CalderaWP/Caldera-Forms#2683]
## Do You Need Immediate Help?
Yes

## Is This A Feature Request?
No

## What Version Of Caldera Forms, WordPress and PHP Are You Using?
Caldera Forms 1.7.2
WordPress 4.9.7
PHP 5.6.33

## Does Your Issue Persist When You Disable All Other Plugins and Switch To The Default Theme?
Yes

## What Is The Unexpected Behaviour?
All of my saved forms are not showing in the Forms panel and shortcodes do not display forms.

## What PHP Errors Have You Logged While Reproducing This Bug?
None

## What JavaScript Errors Have You Seen While Reproducing This Bug?
None

**Comment by jarneson79** [comment]
parsley.min.js?ver=1.7.2:2 Accessing the method 'addValidator' through Validator is deprecated. Simply call 'window.Parsley.addValidator(...)'

**Comment by anna-kirsten** [comment]
Hi - I am having the same problem as you did. Did you find a solution?

**Comment by Shelob9** [comment]
@anna-kirsten What version are you updating from?

I've found this can happen when going from a version before 1.5.6 to 1.7.2. In 1.3.5 we started using a custom table instead of options table for forms. In 1.5.7 we added a test to make sure that table is there, and add it if not. In 1.7 we dropped the options table storage. IF you skipped 1.5.6-1.6.x you may have this issue.

If you can revert to a saved backup before you updated, and then use WP Rollback -- https://wordpress.org/plugins/wp-rollback/ -- to upgrade to 1.5.7 then upgrade to 1.7.2

**Comment by OvidiuZeicu** [comment]
Hello there.

**Comment by Shelob9** [comment]
Sorry to hear you are having this issue. Sounds like you need support. Please open a ticket here and someone from our team can help https://CalderaForms.com/support

**Comment by lucashfreitas** [comment]
Facing the same issue after upgrading to version 1.8.5.

**Comment by bhavi-in** [comment]
Same problem after upgrading to 1.8.5 and it was not from a very old version straight to 1.8.5. It was updated with every new version.

But people using the free version are not eligible for support from Caldera. Funny.

**Comment by OvidiuZeicu** [comment]
Oh come on... this shit still happens? I've reported this issue a year ago, went trough the joke of a "pro" support where I had to wait for days to get an answer and ended up rebuilding the forms, and now this happens again. Really? Screw that... I won't go trough that every time I migrate a site... it's time to cut my losses.

**Comment by mMoovs** [comment]
Same issue here, updated from 1.4.7 to 1.8.9 but lost all the forms, even from the database, the entries are just gone.

So @Shelob9 you're telling us a regular user should be aware of updating in version order? And that there's no migration tool? Updating in version order asks too much from a regular user who is just clicking everything from WP admin and a pain in the ass even if you're using git to manage updates, the migration should be handled via automation because you know the version numbers where the problem **still** exists... 

Luckily I did this on the dev site and not on the production. But now it takes some extra work to revert back to the old version, especially with the database because I need to dig all the relevant entries from the SQL file... Sigh.

**Comment by mMoovs** [comment]
Read throug the changelog and there's no mention about these database changes so it's impossible to know about them without going through the code and I believe there's no user or developer who would do this everytime a new update comes up.

And I'd say this issue is not resolved so it shouldn't be closed.

**Comment by NovyGhani** [comment]
I just experiencing the same thing. I update the Wordpress just now and all forms vanished. Seems like Caldera reinstall and wiped out everything. Will this keep happening if we do the updates? It is worrying if such thing happen. What is the solutions for this? Anyone have any updates on the issue? Thanks

**Comment by Dubidubiduu** [comment]
Argh, I don't want to loose so much time over this again 👎
