### ISSUE TITLE
Resend Not Working

### ISSUE THREAD

**Issue by stlcat** [CalderaWP/Caldera-Forms#3151]
The resend button is not working.  I'm using version 1.8 in wordpress and have guttenberg installed.  I've tried it in IE, Chrome and Firefox with the same non result.

**Comment by strarsis** [comment]
And in Web Development Console I get this error:
````
Cannot find element: #caldera-forms-clippy 
````

**Comment by CoreyBurger** [comment]
I'm also seeing this. Message:
Error: Syntax error, unrecognized expression: #[object Object] load-scripts.php:2:12733
jQuery 10
error
tokenize
select
fa
find
find
find
init
init
n
remove https://DOMAINREMOVED/wp-content/plugins/caldera-forms/assets/js/caldera-clippy.js?ver=1.8.4:76
<anonymous> https://DOMAINREMOVED/wp-content/plugins/caldera-forms/assets/build/js/admin.min.js?ver=1.8.4:1
jQuery 2
dispatch
handle

Wordpress 5.2–en
linked to CiviCRM 5.11.0  (with Caldera Forms 1.0.2)
Caldera forms 1.8.4

**Comment by reeemona** [comment]
Please a "how to.." for Newbies :/ 
What do I have to remove? Where?

Many, many thanks, reeemona

**Comment by SymerSpace** [comment]
I am using Caldera Forms sending mail via the WP Mail SMTP plugin and Gmail API. Email notifications and the autoresponder work fine across all 3 of my forms. But there was a short period when the Gmail API key stopped working. Form submissions are recorded, but emails were not sent. Now I want to resend the emails from forms submitted during that period. 

When I go to the stored data pages and use the Resend button to the right of any record, nothing happens: no error, no redirect. I am trying it on real records as well as those from my test submissions that come from my personal email. Any ideas?

I am also interested to know what gets re-sent. Is it the email notification I have configured to send to staff or the the autoresponder that goes to the customer? Both?

Thanks in advance for any information.

**Comment by mario-neuhold** [comment]
@ksymer I can only confirm that it is re-sending the notification to the staff. Haven't tried it with autoresponders.

As @CoreyBurger pointed out, there seems to be a JS issue here happening when opening the Entries of a form. That probably leads to follow up problems causing the "Resend" button to ignore clicks.

If we change `<button>` to `<a>` in `\plugins\caldera-forms\classes\entry\ui.php Line 201` the resend feature is working as expected.

That's just a quick workaround for the actual JS problem which I haven't found a solution for, yet. Not sure if this is worth a PR already, any thoughts? 
UI wise it doesn't seem to make any difference if it's a button or a tag. Since it's an actual redirect, an a tag might even be more appropriate here in terms of semantics.

**Comment by New0** [comment]
Thank you @stlcat for reporting this issue, and all for participating. 

Thank you @mario-neuhold for the workaround I observed the same marked issue.

**Comment by New0** [comment]
Closed via https://github.com/CalderaWP/Caldera-Forms/commit/831b2c4fc445e48c821ceb354e9da6583f9f00b6
