### ISSUE TITLE
total not showing in the entries

### ISSUE THREAD

**Issue by noahmason101** [CalderaWP/Caldera-Forms#3247]
the output of the total in the calculator elements is always 0  in the entry of my form while it displays the correct result on the webpage

**Comment by New0** [comment]
Hello @noahmason101 , do you test the form as a logged in user ? If not could you login and see if any alert is displayed on top of the form ? Could you share the debug information ?

**Comment by noahmason101** [comment]
I have checked the box for the debug mode but it will not  show anywhere after submitting the entry, there are no errors while I m logged in, and now when I put the form on an online webpage the calculator with manual formula refuses to work, I was thinking about purchasing caldera forms pro to get the email service to work but now with this major issues I can't do that until they are fixed . you will find 2 files below one with internal CSS  code and the other is vanilla, the one with CSS refuses to even import to the website !!!
[json files.zip](https://github.com/CalderaWP/Caldera-Forms/files/3247709/json.files.zip)

**Comment by noahmason101** [comment]
it works fine on the local host preview but in the entry there is no total data and in entry edit the output stays 0 so my best guess is the problem is with the page that reproduces the entry, it does not recognize the manual formula, hile on the online website bothe ( preview and entry preview ) are scrambled .
this is a major bug please fix it before I make a purchase.
[caldera.zip](https://github.com/CalderaWP/Caldera-Forms/files/3247760/caldera.zip)

**Comment by New0** [comment]
Hello @noahmason101 , I'm not so sure. I'd like to determine if this issue comes from an incompatibility of calculation field with recent versions of PHP , a bug ( from the info you shared it could be a bug but not specifically from the calculation field as your calculations involve a lot of field types, magic tags and conditions... ) or that the form you shared requires tuning ( note that this is not a support channel and that would be done via support https://calderaforms.com/support/ ).

Could you share the full debug information from Caldera Forms -> Support under the debug information tab ?

Do you reproduce this behavior with a simple calculation field ? ( like 
[calculation-simple-export.zip](https://github.com/CalderaWP/Caldera-Forms/files/3251418/calculation-simple-export.zip) )

**Comment by noahmason101** [comment]
I don't know why but I love you man , I have spent the last 48 hours troubleshooting this but , and when I saw your example I had the idea of eliminating all the HTML and CSS code: 1- boom first problem solved, your importer doesn't allow CSS or HTML or both (not major issue I can live with that ! 
then I revised the values and the calculation values of each element: 2- the second problem solved, your importer did reset all calculation values to 0 which did override the value.
so basically I and the importer were a mix of vomit made to trouble your peace, sorry for that bro,
[caldera debug 2.zip](https://github.com/CalderaWP/Caldera-Forms/files/3253960/caldera.debug.2.zip)
 but you have to mention this minor bug to the users so they will not make the same mistake.
BTW I m' an architecture student in a third world country, I had to teach myself basic programming just for this form and again I love you, men, and whenever my website makes a revenue I 'll bye your enterprise offer even though I don't need it, it's just you deserve a lot more, your plugin is pure gold.

**Comment by New0** [comment]
Hello @noahmason101 , thank you for these kind words, don't hesitate to share them in a review at https://wordpress.org/support/plugin/caldera-forms/reviews/#new-post !

I'm really glad you got it working, it is a powerful plugin that have the largest possibilities of configurations, that's why it requires extra attention to all details. I wish you the best for your studies and the website.
