### ISSUE TITLE
List add-ons in admin

### ISSUE THREAD

**Issue by New0** [CalderaWP/Caldera-Forms#3394]
List add-ons under the Get More tab =>
![Screenshot_2019-11-11 Caldera Forms Admin ‹ Local — WordPress](https://user-images.githubusercontent.com/16348693/68583872-88754a80-047e-11ea-8d9b-614b3b5afa96.png)

**Comment by Shelob9** [comment]
@New0 This will have to be fixed in wp-content/plugins/calderawp_api on CalderaForms.com that plugin provides the REST API endpoints for that section of the UI. The WP_Query args in the API endpoints have all sorts of extra items to support that and the old site add-ons search. 

It is highly likely that the new downloads are not in the returned API response.

**Comment by New0** [comment]
Thanks @Shelob9 , closing as this will be worked on the websites side.
