### ISSUE TITLE
Advanced File Field 2.0 does not display the description set in the field

### ISSUE THREAD

**Issue by New0** [CalderaWP/Caldera-Forms#3542]
The description option field in the advanced file field 2.0 is showing as expected in the preview but not on frontend.

Settings view: (description displayed)
![Screenshot_2020-05-22 Caldera Forms Admin ‹ VSLAN — WordPress](https://user-images.githubusercontent.com/16348693/82665765-c5dc4100-9c34-11ea-9a9b-322928f26cbd.png)

Form view: (no description)
![Screenshot_2020-05-22 Contact – VSLAN](https://user-images.githubusercontent.com/16348693/82665772-c83e9b00-9c34-11ea-8921-d460cfd45887.png)

**Comment by valber-figueiredo** [comment]
Okay Nicolas these your name correct?

Really thanks for the support.

You speak Portuguese? If so, can we talk in Portuguese?

About problem in Advanced File Field I suffered this problem about a month ago and I ended up not trying anymore ... And also other problems I also tried for a while and gave up after no answers ...

So I installed Formidable plugin again and configured it.

And so now I got in touch with you and reactivated the caldera forms on the site together with Formidable, both of which are active.

And I noticed that Advanced File Field now works normally in the description below the uploud box.

So I believe it was a conflict with some plugin or something I didn't discover.

So in this case we can consider this issue as SOLVED because it is now working.

image: https://ibb.co/L13d2MJ

**Comment by New0** [comment]
Hello @valber-figueiredo , thank you for the details. I'm closing this issue. Take care!

PS: I wish I'd speak Portuguese but that's not the case. But even if I did, that would complicate the repository communication if we used multiple languages and it's preferable to stick to our international English no matter what level
