### ISSUE TITLE
Form Saving Broken After 1.9.0 Update

### ISSUE THREAD

**Issue by GreenRooster** [CalderaWP/Caldera-Forms#3570]
## Do You Need Immediate Help?

N/A. Rolled back to working 1.8.11

## Is This A Feature Request?

No

## What Version Of Caldera Forms, WordPress and PHP Are You Using?

**Short Debug Information**
    WordPress Version: 5.4.2  |  PHP Version: 7.3.18-1+ubuntu18.04.1+deb.sury.org+1  |  MySQL Version: 5.7.29  |  Caldera Forms Version: 1.9.1  |  WP_DEBUG: 1

## Does Your Issue Persist When You Disable All Other Plugins and Switch To The Default Theme?
Yes

## What Is The Unexpected Behaviour?

Upon updating from 1.8.11 to 1.9.0 & 1.9.1, we have been unable to save either newly created forms or existing forms. We use post names for our permalinks. If we change permalinks to plain, things function properly. However, that is not an acceptable solution. Seems like a similar error to #3568.

In a fresh install on another testing site with the below debug settings, everything works as normal. Which is great, except I can't change some of what my host allows.

WordPress Version: 5.4.2  |  PHP Version: 7.4.1  |  MySQL Version: 8.0.16  |  Caldera Forms Version: 1.9.1

## What PHP Errors Have You Logged While Reproducing This Bug?

None.

## What JavaScript Errors Have You Seen While Reproducing This Bug?

Request URL: ***/wp-json/cf-api/v2/forms/undefined?_locale=user
Request Method: POST
Status Code: 404 Not Found

code: "invalid_json"
message: "The response is not a valid JSON response."

**Comment by New0** [comment]
Than you for reporting this issue @GreenRooster 

@Shelob9 I could reproduce an issue saving the form when testing PR #3576 ( 

The investigation so far resulted in:

1. The API route set in classes/api/forms.php is not overriding the route from classes/api/crud.php
I believe the route set in classes/api/forms.php should be targetted in order to call save_form($request) l116

It is not the case in PR #3576 where clicking the Save button in a Form edition page targets the Route in classes/api/crud.php and calls update_item( $request) l254 which is currently set to not_yet_response(); ( as a route from crud ).

2.  The handleSave() in clients/form_builder/index.js l71 is called without a form_id which results in calling an API route as "forms/undefined"

I opened  PR #3581 to illustrate this issue combined with the fix for Privacy settings and entries edition.

**Comment by andyburnsco** [comment]
Saving permalinks made the save function work for me.

**Comment by New0** [comment]
Closed via https://github.com/CalderaWP/Caldera-Forms/commit/9849137d9741ff5931c9464c2589044cd8fd51c7
