### ISSUE TITLE
Dont load assets in pages where no forms preset

### ISSUE THREAD

**Issue by lmartins** [CalderaWP/Caldera-Forms#407]
Not necessarily an issue, more like a enhancement suggestion.
Pages where no form is present shouldn't be loading assets such as the Parsley library.

**Comment by Shelob9** [comment]
This is no longer an issue.

**Comment by reemzid** [comment]
I am using Caldra form in Wordpress in our website for long time but when i am trying to add a the option dropdown menu or autocomplete there is an option for preset i am when i choose this option it used to work now when i choose and save the form there is nothing appearing in the dropdown. No data at all showing. 
Please help me with this because a lot of form in our website has country listed and i can not possibly enter one by one.

**Comment by reemzid** [comment]
hello @DavidCramer , any solution or suggestions for me ? 
Thank you
