### ISSUE TITLE
Value coming from the dropdown is incorrect in emails

### ISSUE THREAD

**Issue by unijewski** [CalderaWP/Caldera-Forms#542]
Hi guys, 
I found out a bug related to the dropdown select element. If I set a value for the label in the dropdown option then in the email message instead of `name` displayed I get `ID`. For example:
```
Value Label
===========
0     Male
1     Female
```
Then for this label I get `0` or `1` assigned instead of `Male` or `Female`. 

There's also a similar case but I'm not sure whether it's intentional. When I check `Auto Populate`, `Auto Type: Post Type` and `Value: ID` for the dropdown I also get ID in the email message. Maybe is it worth considering to change it to `name` as well?

Cheers.

**Comment by Shelob9** [comment]
Related #567 #568

**Comment by Desertsnowman** [comment]
I'm totally against this. By definition setting the value to be something different, is stating that this is the value to use and the label is what is shown to the user. This is how a select is defined as and works- see http://www.w3schools.com/tags/att_option_value.asp

if you really want the lable in the email, then dont set a value, or set up a manual message rather than the `{summary}` and use `%select_slug|label%` where needed.

I'm so tempted to put a notice when the "Show Values" is checked stating that the value is what is saved, not the label.
