### ISSUE TITLE
Import/Export bugs

### ISSUE THREAD

**Issue by ghost** [CalderaWP/Caldera-Forms#580]
Boy where do I start? I'll just report things as they happened in hopes it helps reproduce:
In latest release version of CF on a client site, I cloned a simple form (half dozen fields, redirect and  mailer), then went in to edit the form's HTML content. I updated and saved the form, then clicked form...

BUG 1: When I returned to the list there were 2 identical forms, indicating the update and clone operations iterated after navigating away (since the form content was the same).

Apparently the original form had been previously cloned or cloned itself; There was an extra, identical version to the working form (which had 2 entries). I deleted the extra one that had no entries. Page refreshed and only the form without entries (the one I didn't delete!) remained. So...
BUG 2: the form entries displayed don't seem to necessarily align with what's in the database, or URLs presented. This led me to delete the working version accidentally... and worse...
BUG 3: refreshed page, both forms gone!

Now things get weirder. We have a staging site for this client with WPengine, so I have the original form there. I figured I'd export it from CF in the dashboard, then import it to the staging site where it had previously blown up. I opened Export tab, clicked export (dialog box was empty), let it spin. 
BUG 4: No exported file appears, export seems broken.

So something in CF or this installation is munged. I'm taking over for another developer on this, and there are lots of hairy bits of code hanging around, however CF was installed by me and only has a couple forms (basically contact forms), so it's not bumping into itself or older content.

**Comment by dlincoln** [comment]
Insight on BUG 3 and 4: The export selector with options appears on the live site for the version of the form that has no entries, while I get a blank requester (and no file) on the form with 2 entries. 

So it would appear that the database links to the form content is getting scrambled/split. There's really only one form -- the one that shows no entries but is exportable. Both are editable. But only one can be exported and is a valid form, the other the only valid call back.

This may also resolve BUG 2.

**Comment by dlincoln** [comment]
For whatever reason I can't clone or import a form without getting the double forms on my installation with 1.3.5. I suspect this is database related: when I import a deleted form, it seems to revive the double entry, Or something like that. At any rate the app is kind of useless at the moment, since I can't manage the spawn of clones (and cloning forms is my thing at the moment). Not sure when it broke, but I did update it pretty recently.

**Comment by dlincoln** [comment]
I'm seeing this bug again in 1.3.5.3 -- it seems like it's state-related, since it's not constant. In most cases, when you clone a form, make your changes, then update and return to "Forms" on the dashboard, I see TWO copies of the form, which are identical. But I think this is just the display: When you edit either form, both are edited!

At any rate it's making life kind of weird.

WORKAROUND: EXPORT forms, then IMPORT, and don't use clone. Seems to avoid the issue (and may provide a clue).

**Comment by Desertsnowman** [comment]
Pushed to 1.3.7 since I'm sure I fixed a part of this but don't want to get involved with exports right now.
And since there is a workaround that is not massively complex, its fine for now.

**Comment by Brian-Milnes** [comment]
If it's related, I have isolated a problem Exporting a Form if it has a Processor attached.
(Workaround to Clone then Rove Processor then Eport Import)
