### ISSUE TITLE
Entries for form not displaying 

### ISSUE THREAD

**Issue by bustapaladin** [CalderaWP/Caldera-Forms#632]
And this is simply fixed by adding as default "1" and not leaving it empty.

undefined items « ‹  
 of 1 › »
No entries yet.

**Comment by Shelob9** [comment]
@bustapaladin It looks like we lost part of your message. Can you please edit your issue?

**Comment by bustapaladin** [comment]
Here is a good gif picture to illustrate the bug: https://i.gyazo.com/478ee8ece4a085e66e36c77a2abb8b5d.gif

**Comment by Shelob9** [comment]
Can you please check your console for JavaScript errors, and also provide us with the version of Caldera Forms and WordPress you are using?

**Comment by bustapaladin** [comment]
No console errors and using the latest version of your plugin. I'd let you also know that if you chose to have a separate menu for the entries they do show up fine but that its only in the form list when you click entries this bug happens.

**Comment by Shelob9** [comment]
@bustapaladin By `latest version of your plugin` do you mean 1.5.3 or 1.3.6-b3 ?

**Comment by bustapaladin** [comment]
I mean 1.5.3

**Comment by Shelob9** [comment]
@bustapaladin Is there anyway you can test with the latest version (currently 1.3.6.-b3) please? We've done a ton of work on entry viewer since 1.5.3. I'd like to know if you are having these issues on the latest version or not.

That said, none of these issues are present in 1.5.3 for me, so I suspect you are having a theme or plugin conflict. Hard to say since I don't know what errors your getting. If you could test with 1.3.6-b3 while logging PHP errors and with the JavaScript console open, that would be great.

**Comment by bustapaladin** [comment]
How do I install the latest version and is this just deleting the old plugin and adding this? Or how does an upgrade work? I usually just hit update and don't think much further then that when a new version is out.

Also I can confirm this is a real bug in 1.5.3 as I've just tested it on my test blog with only 5 plugins active.

**Comment by Shelob9** [comment]
@bustapaladin https://calderawp.com/doc/update-caldera-forms-latest-beta/

**Comment by bustapaladin** [comment]
Installing the latest beta made the page show up alright for my editor. only not the entries...

https://i.gyazo.com/4e3e8b8b76519f45495f630e14540bef.gif
