### ISSUE TITLE
Calculation fields in 1.3.5.x

### ISSUE THREAD

**Issue by Shelob9** [CalderaWP/Caldera-Forms#658]
We have some reports of calculation issues not working properly client side. David blames his denounce.

I have one report (helpscout #175) of a PHP runtime error generated by calculation error. That sounds like an invalid magic tag was used, but still we should prevent against that.

**Comment by Desertsnowman** [comment]
@Shelob9 - I was wrong, the debounce is fine although a little slow at times. The problem was what you said; invalid magic tags.

Best way to prevent is to not show the system magic tags as an option and only show fields. that way it forces the user to use a hidden field ( the correct way to do it ) to get the value to be used in the calculation.
