### ISSUE TITLE
Feature Requests

### ISSUE THREAD

**Issue by omniacode** [CalderaWP/Caldera-Forms#696]
Hey guys, after switching to using Caldera Forms primarily over CF7 and using it quite a bit now, I have a few UI/Enhancements I would like to request that would make life a little easier using the plugin.

1. Place to put reCaptcha API Keys to be used across all forms. Having to re-enter these on a per-form basis is rather cumbersome. Typically a site uses the same API Keys for every form so it makes sense to have a global setting for this.
2. Disabling Hide Form - When this is disabled, the alerts show at the top of the form and if they are out of view, you don't see them after submission unless you scroll back up to the top of the form. Would be nice if by default on disabling this, an onSubmit fired with a scrollTo function to automatically scroll back to the top of the form. Or just move alerts to the bottom of the form by the Submit buttons.
3. Wrapper Class - For styling purposes, would be nice if there was a field that you could enter that wraps the entire form to make for easier targeting when styling forms. Could target the parent of the containing div, but this would make it easier for rapid development since I have SASS classes set up for the forms now I transfer site to site.

Thanks a bunch, great work on this plugin.

**Comment by Shelob9** [comment]
@omniacode Thanks for using Caldera Forms.

> 1. Place to put reCaptcha API Keys to be used across all forms....
We are going to add an API key manager for our payment/newlsetter processors in the next version after the one we are working on. It will not support reCaptcha fields. We discontinued those awhile ago since our default anti-spam is more effective and doesn't hurt conversions like reCaptcha fields do.

#329


> 2. Disabling Hide Form - When this is disabled, the alerts show at the top of the form and if they 

I agree. I find this annoying to. I'd like to get a fix for it in soon.


> 3. Wrapper Class - For styling purposes, would be nice if there was a field that you could enter that wraps the entire form to make for easier targeting when styling forms.
By default the form is wrapped in an element with the class "caldera-grid" you can modify that using the `caldera_forms_render_form_wrapper_classes` filter. See: https://calderawp.com/doc/caldera_forms_render_form_wrapper_classes/

**Comment by Shelob9** [comment]
BTW  @omniacode I am closing this for reasons of tidiness -- it's not an issue/bug. Feel free to continue discussion.
