### ISSUE TITLE
field options unique check, not bound to current field.

### ISSUE THREAD

**Issue by mariahclark** [CalderaWP/Caldera-Forms#731]
I just updated and my form that was working isn't.

1st issue many items that were required aren't any more. 

2nd issue several of my questions are now showing up in red when I try to save. I have tried everything but I can't get them to work. I have tried new slugs. I have tried deleting and reentering them. It doesn't like those questions, so I can't update any changes to the form. There is no error message except highlighting the questions in red. The same questions worked in the last version. I should have backed it up but I didn't is there anyway to go back to the old version?

**Comment by Desertsnowman** [comment]
@mariahclark - can you send me a link to the form so I can see what it's doing?

**Comment by mariahclark** [comment]
The site is not live and the problem is in the back end. 
1st these were all required before the update. 
![red box](https://cloud.githubusercontent.com/assets/8061537/17246262/e906616e-5558-11e6-9a85-0f9ccef0d152.PNG)
2nd it saved fine before the update. All I did to get those boxes was open the saved form and hit save again.
3rd. I can't figure out why it isn't letting me save. 
![filled in](https://cloud.githubusercontent.com/assets/8061537/17246294/13f88190-5559-11e6-8ba4-31a58883c4a5.PNG).

**Comment by Desertsnowman** [comment]
@mariahclark - I see the problem and it is a bug introduced. I have a patch, and will update ASAP

**Comment by mariahclark** [comment]
Thanks I will keep my eyes open for the update. I am glad you could find it from the screen shots.

**Comment by Shelob9** [comment]
@Desertsnowman I am testing with a different form with same issue. With current-stable checked out after this update, it is not resolved. I am sending this export to you in Slack.

**Comment by Shelob9** [comment]
Confirmed as fixed, but requries a cache clear because version number was not changed.

**Comment by 101010f** [comment]
Having the same issue even after the update. The error message doesn't show anymore but the red border around the value field still appears when using same value.

**Comment by mariahclark** [comment]
1.4.1 fixed my issue. It isn't return my required fields I don't know why they disappeared, but it let me recheck the boxes so my form is working again. Thank you!

Is there somewhere I can post a suggestion. I have an idea for the slider option.

**Comment by Desertsnowman** [comment]
@101010f  - the bug was having the an option with the save value as another option based field.
On a single field, you cannot have duplicate values on an option.

**Comment by 101010f** [comment]
@Desertsnowman - I don't know why I posted this here in the first place. (should I open a new issue?) I'll try to be a bit clear on this. Prior to 1.4.0 I had a checkbox field with multiple options. Some options had the same value (price) and it worked. After 1.4.0 it won't let me save and gives this error: https://postimg.org/image/7bukk3d93/

**Comment by Desertsnowman** [comment]
@101010f - that is correct. it was working because it was a bug.
I made the change to stop allowing this.

Let me explain the reasons.
The value, as per the definition of a value, is the value in which the option represents.
So lets say, in your example, that someone buys "some product 2" the value "99" is sent to the server since this is what was selected.|

Now when you get the email saying that someone bought "99" there is no way to know which 99 was actually selected since there are 2 of them.

Essentially, every "bug" report we get saying that the checkbox/dropdown/radio label is not the correct one, is down to the fact that people are using the value field incorrectly.

The correct way to do a option/price thing is to use hidden fields with the value and use conditionals to show and hide them based on the selection.

**Comment by 101010f** [comment]
@Desertsnowman - I followed this video tutorial back then > https://www.youtube.com/watch?v=v3NTBvXeknA and it seems the value field is the price, right?
