### ISSUE TITLE
Button Next page  and  previous page doesn't work

### ISSUE THREAD

**Issue by readcom** [CalderaWP/Caldera-Forms#782]
Hello, Button Next page  and  previous page doesn't work, Caldera Forms vers. 1.4.1 and Wordpress 4.6.,
doesn't matter if I have all fields filled up.

please fix it, thanks.

**Comment by Shelob9** [comment]
@readcom I'm sorry you are having this issue on your site. But because it is an issue with your site, not with the plugin -- page buttons work fine with just Caldera Forms 1.4.1 + WordPress 4.6 and TwentySixteen, you need to open a support ticket and provide all of the requested information so we can help you troubleshoot this issue:

https://CalderaWP.com/support
