### ISSUE TITLE
checkbox/radio numeric value for calculation?

### ISSUE THREAD

**Issue by 101010f** [CalderaWP/Caldera-Forms#805]
Any chance you'll add a numeric value for checkboxes/radio for calculating? Adding hidden fields and conditions for every checkbox is really time and resource consuming.

**Comment by Shelob9** [comment]
I'm confused about what you're asking here. Vales for check boxes and radio
can be numeric if you want.

**Comment by 101010f** [comment]
Yes, I know as per this tutorial https://www.youtube.com/watch?v=v3NTBvXeknA . But right now duplicate values are not allowed. They used to be but no more. And as David Cramer stated in a previous issue:

> The value, as per the definition of a value, is the value in which the option represents.
So lets say, in your example, that someone buys "some product 2" the value "99" is sent to the server since this is what was selected.|

Now when you get the email saying that someone bought "99" there is no way to know which 99 was actually selected since there are 2 of them.

Essentially, every "bug" report we get saying that the checkbox/dropdown/radio label is not the correct one, is down to the fact that people are using the value field incorrectly.

The correct way to do a option/price thing is to use hidden fields with the value and use conditionals to show and hide them based on the selection.
>

**Comment by Shelob9** [comment]
@101010f  We can keep discussing here, but, I'm closing this because it is not really an actionable issue and I want to keep issue tracking cleaner.

You raise a couple valid points:
* `But right now duplicate values are not allowed. They used to be but no more.`
Right, we used to let you you do that, but it led to all sorts of bad bugs. I really didn't want David to make it the way it is now, but eventually agreed he was right.
* `Now when you get the email saying that someone bought "99" there is no way to know which 99 was actually selected since there are 2 of them.`
Right. That is not great. You can use %field_slug:label% type, magic tags. But then you can't use `{summary}` so that's not a great solution. My proposed solution is an option to use labels, not values in `{summary}` magic tag: #806

**Comment by 101010f** [comment]
Ninja Forms uses 3 values for it's multi select radio/checkboxes: 'Label', 'Value' and 'Calc value'. Would this interfere with anything else in the plugin?
