### ISSUE TITLE
Form Settings tab had gotten messy and is in a bad order

### ISSUE THREAD

**Issue by Shelob9** [CalderaWP/Caldera-Forms#938]
Related #930

**Comment by paaljoachim** [comment]
Order of importance as I see it...
Form Name
Shortcode
Form Description

Success Message --- Should this really be inside the Form Settings? What about adding it into the Processors section instead? So that we have it alongside the Auto Responder.

Hide Form
Honeypot

Show Entry View Page (in Forms screen)?
View Entries.

Further down:
Capture Entries meaning one can globally enable or disable show in entry list? Not sure if I grasp this one.
State.... which one? Should be a better name here. 
Gravatar Field. Not sure of the use of this one.
Ajax Submissions.
Multiple Ajax Submissions.

**Comment by Shelob9** [comment]
Close via 	
f677fe7
b3bc6e2
	4367fc9
